.TH javaws 1 "23 Aug 2014"
.SH NAME
javaws - a Java Web Start client
.SH SYNOPSIS
.B javaws
[-run-options] jnlp-file
.br
.B javaws
[-control-option]
.SH DESCRIPTION
.B javaws
is an implementation of a JNLP  client. It uses a JNLP (Java Network
Launch Protocol) file to securely run a remote Java application or
a Java applet.  This implementation of
.B javaws
is from the IcedTea project and is based on the NetX project.
.PP
A JNLP file is an XML file that describes how to securely run a
remote Java application or a Java applet.

.SH OPTIONS
When specifying options, the name of the JNLP file must be the last
argument to
.B javaws
- all the options must precede it.
.PP
The JNLP-file can either be a URL or a local path.
.PP
.B Control Options
.PP
By default
.B javaws
will launch the JNLP file specified on the command line. The control
options can be used to change this behaviour.
.TP 12
\-about
Shows about dialog.
.TP
\-viewer
Shows the trusted certificate viewer. This allows a user to list, examine, remove
or export trusted certificates. Note that this only reflects the certificates
trusted by
.B javaws
and not any other certificates or programs.

.PP
.B Run Options
.PP
In the default mode, the following run-options can be used:
.TP 12
\-version
Prints out version and exit
.TP
\-arg arg
Adds an application argument before launching.
.TP
\-param name=value
Adds an applet parameter before launching.
.TP
\-property name=value
Sets a system property before launching.
.TP
\-update seconds
Check for applet/application updates if "seconds" seconds have elapsed since the last check.
.TP
\-license
Display the GPL license and exit.
.TP
\-verbose
Enable verbose output. Very useful in debugging.
.TP
\-nosecurity
Disables the secure runtime environment.
.TP
\-noupdate
Disables checking for updates.
.TP
\-headless
Disables the download window and other extra UI elements.
.TP
\-strict
Enables strict checking of JNLP file format. Any deviations from
the JNLP DTD will cause
.B javaws
to abort.
.TP
\-xml
Enables stricter XML validity checking for JNLP files.
.TP
\-allowredirect
Enables following 301, 302, 303, 307 and 308 HTTP redirects for
.B javaws
applications.
.TP
\-Xoffline
IcedTea-Web will not attempt to connect to the network to check for or download
newer versions of the requested applet or application. Locally cached application
files will be used instead, if available. The application itself may still
establish its own network connections.
.TP
\-Xnofork
Do not create another JVM, even if the JNLP file asks for running in
a separate JVM. This is useful for debugging.
.TP
\-Xclearcache
Clean the JNLP application cache.
.TP
\-Xignoreheaders
Skip jar header verification.
.TP
\-Jjava-option
This passes along java-option to the Java binary (JVM) which
.B javaws
will be executed within. For example, to make
.B javaws
run with a max heap size
of 80m, use -J-Xmx80m.
.TP
\-help
Print the
.B javaws
help message and exit.

.SH FILES
$XDG_CONFIG_DIR/icedtea-web/deployment.properties specifies the settings used by
.B javaws

$XDG_CONFIG_DIR/icedtea-web/log (may be set to different location by you) contains file log files (if enabled).
itw-cplugin-date_time.log for native part of plugin, itw-javantx-date_time.log for everything else.

$XDG_CONFIG_DIR/icedtea-web/security/java.policy contains the user's security policy, which may grant extra permissions to applets.

$XDG_CONFIG_DIR/icedtea-web/security/trusted.*certs contains various stored certificates.

$XDG_CACHE_DIR/icedtea-web/cache contains cached runtime entries (may be modified by the user).

$XDG_CACHE_DIR/icedtea-web/pcache contains saved application data.

$XDG_CACHE_DIR/icedtea-web/tmp contains temporary runtime files.

$XDG_RUNTIME_DIR/icedteaplugin-user-*/ contains in and out pipe for native<->java communication and
(if enabled) debugging pipe

Where $XDG_CONFIG_DIR, $XDG_CACHE_DIR and $XDG_RUNTIME_DIR are defined as $HOME/.config, $HOME/.cache and either /tmp or /var/tmp by default.
This is in accordance with the FreeDesktop Base Directory Specification:
    http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

.SH BUGS
There aren't any known bugs. If you come across one, please file it at
    http://icedtea.classpath.org/bugzilla/
.br
Please run
.B javaws
in debug (via -verbose switch, 
.B itweb-settings
configuration, or ICEDTEAPLUGIN_DEBUG environment variable set to true)
mode and include that output (best is from java console) with URL to JNLP or HTML file
(not the JNLP/HTML file or application itself) when filing out the bug report.

.SH AUTHOR
Originally written by Jon. A. Maxwell.
.br
Currently maintained by the IcedTea contributors. See javaws -about for more info

.SH SEE ALSO
.BR java (1), 
.BR itweb-settings (1)
.br
http://icedtea.classpath.org/wiki/IcedTea-Web
